mapeamento = {
    "sp": "São Paulo (SP)",
    "rj": "Rio de Janeiro (RJ)",
    "bh": "Belo Horizonte (MG)",
    "bs": "Baixada Santista (SP)",
    "valedoparaiba": "Vale do Paraíba (SP)",
    "sorocaba": "Sorocaba (SP)",
    "campinas": "Campinas (SP)",
    "sl": "São Luís (MA)",
    "df": "Distrito Federal (DF)",
    "goiania": "Goiânia (GO)",
    "recife": "Recife (PE)",
    "salvador": "Salvador (BA)",
    "fortaleza": "Fortaleza (CE)",
    "curitiba": "Curitiba (PR)",
    "manaus": "Manaus (AM)",
    "natal": "Natal (RN)",
    "teresina_timon": "Teresina/Timon (PI/MA)",
    "maceio": "Maceió (AL)",
    "belem": "Belém (PA)",
    "cuiaba": "Cuiabá (MT)",
    "pa": "Porto Alegre (RS)",
    "petrolina_juazeiro": "Petrolina/Juazeiro (PE/BA)",
    "florianopolis": "Florianópolis (SC)"
}
